# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('restapi', '0001_initial'), ('restapi', '0002_auto_20171010_1531'), ('restapi', '0003_auto_20171011_0527')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('excerpt', models.CharField(blank=True, max_length=64, null=True, verbose_name='Excerpt')),
                ('created_at', models.TimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_unread', models.BooleanField(default=True, verbose_name='Is unread?')),
            ],
        ),
    ]
