# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_sorting_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='excerpt',
            field=models.TextField(blank=True, null=True, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
    ]
